return PlaceObj('ModDef', {
	'title', "Stargate",
	'description', "Stargates allow Tourists to instantly travel to Mars, giving them a Satisfaction boost!  Readme: https://github.com/Surviving-Mars-Mods/Stargate-Tours",
	'image', "Images/thumbnail.png",
	'last_changes', "https://github.com/Surviving-Mars-Mods/Stargate-Tours",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"src/*",
		"*.iml",
		".idea/*",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "FIZZLE1",
			'title', "Fizzle Fuze's Library",
			'version_major', 1,
			'version_minor', 7,
		}),
	},
	'id', "FFStargate",
	'steam_id', "",
	'pops_desktop_uuid', "",
	'pops_any_uuid', "",
	'author', "Fizzle_Fuze",
	'version_major', 1,
	'version_minor', 1,
	'version', 41235,
	'lua_revision', 1009413,
	'saved_with_revision', 1010838,
	'code', {
		"Code/Code.lua",
		"Code/BuildingTemplate.lua",
		"Code/Stargate.lua",
	},
	'saved', 1645033554,
	'has_options', 'true',
})
